### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Karanztez** [bptube/BPSignShop#4]
When I closed server and opened it, I had to set up a new store.

**Comment by bptube** [comment]
I did not understand you well, the store disappeared when you turned off the server?
If I generate an error please put it here

**Comment by Karanztez** [comment]
Yes, the shop disappeared after closing and reopening.

Like the system will not save data

**Comment by Karanztez** [comment]
ID : 91 Pumpkin glowing, the name is too long, can not be sold or has a special form

**Comment by bptube** [comment]
`Yes, the shop disappeared after closing and reopening.`

I just tried this and had no problems (Create two stores of each, I closed the server and opened it and they were still working)

`ID : 91 Pumpkin glowing, the name is too long, can not be sold or has a special form`

I'll see how to solve this, thanks for reporting

**Comment by bptube** [comment]
The error of the name is solved.
https://ibb.co/B3nFrpX
I will investigate the other one although I did a lot of tests and it did not happen.

**Comment by bptube** [comment]
I know why the error is generated that causes stores to be deleted.

**Comment by bptube** [comment]
Solved. Unfortunately stores created previously are not compatible

**Comment by Karanztez** [comment]
Thanks
